spring:

  # Database Setting Info
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pet_clinic?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

  # JPA Setting Info
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
      show-sql : true

  # Logging
  logging:
    level:
      org.hibernate.SQL: debug

  # Security
  spring:
    security:
      user:
        name: admin
        password: 1234
        roles: USER, ADMIN